### ISSUE TITLE
Error in get_info

### ISSUE THREAD

**Issue by jebyrnes** [debusklaneml/VirginiaC19#2]
```
> library(VirginiaC19)
> get_info_VirginiaC19()
Error in file(file, "rt") : 
  cannot open the connection to 'https://www.vdh.virginia.gov/content/uploads/sites/182/2020/03/VDH-COVID-19-PublicUseDataset-Cases.csv'
```

**Comment by jebyrnes** [comment]
Similarly:
```
>  latest_data <- refresh_VirginiaC19(verbose = TRUE)
Downloading raw data from https://www.vdh.virginia.gov/content/uploads/sites/182/2020/03/VDH-COVID-19-PublicUseDataset-Cases.csv.
Error in file(file, "rt") : 
  cannot open the connection to 'https://www.vdh.virginia.gov/content/uploads/sites/182/2020/03/VDH-COVID-19-PublicUseDataset-Cases.csv'
```

**Comment by debusklaneml** [comment]
@jebyrnes I've been fighting with these errors for a while now through my failed Travis build ([here](https://travis-ci.org/github/debusklaneml/VirginiaC19)). I also have an open Travis forum post ([here](https://travis-ci.community/t/testthat-cannot-open-the-connection-to/8569)). 

I have, essentially, mirrored code to my CanadaC19 package for reading in the data from an active URL, but for whatever reason, the build does not like it here. It passed all of my own devtools tests/checks perfectly fine, which leads me to believe its an environment issue (although my CanadaC19 package works fine through Travis). 

Any suggests on a better way to debug this through either Travis or myself? 

Thanks.

**Comment by jebyrnes** [comment]
So, the error here is that the URL for the file has moved. Right? Should be a quick fix, no?

**Comment by debusklaneml** [comment]
Well, Virginia did change their url, but even after updating the url in my code, I encounter the same problem I've been having with this from the beginning. 

Here are my clues:
'unable to open the connection to... "https://www.vdh.virginia.gov/content/uploads/sites/182/2020/05/VDH-COVID-19-PublicUseDataset-Cases.csv" using both utils::read.csv() and readr::read_csv(). 

I also just tried data.table's 'fread' function, which produces a 

"SSL certificate problem: unable to get local issuer certificate
Backtrace:
1. VirginiaC19::refresh_VirginiaC19()
5. VirginiaC19:::read_data()
8. data.table::fread("https://www.vdh.virginia.gov/content/uploads/sites/182/2020/05/VDH-COVID-19-PublicUseDataset-Cases.csv")
9. curl::curl_download(input, tmpFile, mode = "wb", quiet = !showProgress)

It appears, that in some environments, the URL is not opening to the package when called. 

Any ideas @jebyrnes 

Thanks.

**Comment by debusklaneml** [comment]
Ok, I believe I've narrowed this issue down to an url SSL certificate problem when Travis sends the request through readr for the file, the build does not contain the appropriate certificate. All my local env. builds work great. 

@jebyrnes are you requiring a passing Travis for this project? 

If so, I'll develop a GitHub action to pull the data down into a repository and build the package to pull from my own repository to navigate away from this url issue.

**Comment by jebyrnes** [comment]
Nope! I just want to be able to run it! We also need it to be able to run on github actions, but we can cross that bridge when we come to it. It just didn't run for me when I ran it on my own laptop initially. LMK when I should check again!

**Comment by debusklaneml** [comment]
I'm working the other smaller issues right now, but it should be good later tonight. The issue you encountered was because Virginia updated their link... which has been fixed.

**Comment by debusklaneml** [comment]
@jebyrnes I adjusted the data file to be tidy across all three types of data in the file and used the standardized library. Check it out.
